+paulfitz.github.io/daff
pkgxdev/pantry pull request #1836
Opened 2023-05-04 22:30 UTC by magnusviri

The source code is Haxe. I looked at packaging that up but it's a doozy. Because it's Haxe, the developer has published other versions, in this case, the python version is on Pypi. That's why I'm pointing to that source. I'm also hardcoding the version because the developer hasn't updated the Pypi version to the latest listed on GitHub.

2023-05-08 13:40 UTC, mxcl commented
If you mark them as ready when done then people on the team other than me will see it is ready and merge.

2023-05-08 13:41 UTC, mxcl commented on projects/paulfitz.github.io/daff/package.yml
> +  #github: paulfitz/daff/tags
add this, but set an `ignore` for versions you don't want.

2023-05-08 13:41 UTC, mxcl requested changes

2023-05-08 13:41 UTC, mxcl commented on projects/paulfitz.github.io/daff/package.yml
> +  python.org: '>=3.7'
More likely ^3.7 since this will use v4 if and when it is released

2023-07-01 06:59 UTC, magnusviri commented
Sorry to take so long to get to this. I've been pretty distracted lately. GHA looks slow. If it passes it's ready. I'll mark it as ready.

2023-07-01 18:28 UTC, jhheider commented
No apologies needed, @magnusviri . We respect your time spent. :)

2023-07-01 18:29 UTC, merged