fix(ruby-lang.org)
pkgxdev/pantry pull request #4875
Opened 2024-01-17 02:30 UTC by scottjg

it appears there are a few hardcoded paths from ci that made it into the packaged rbconfig.rb. this breaks installation of gems that require native compilation. so, lets patch that up

2024-01-17 02:36 UTC, scottjg commented
here was the error i ran into installing a gem:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.2.0/gems/rinku-2.0.6/ext/rinku
/Users/scottjg/.pkgx/ruby-lang.org/v3.2.2/bin/ruby -I/Users/scottjg/.pkgx/rubygems.org/v3.5.4/lib extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/3.2.0/gems/rinku-2.0.6/ext/rinku
make DESTDIR\= sitearchdir\=./.gem.20240116-77598-2ir1kp sitelibdir\=./.gem.20240116-77598-2ir1kp clean

current directory: /usr/local/lib/ruby/gems/3.2.0/gems/rinku-2.0.6/ext/rinku
make DESTDIR\= sitearchdir\=./.gem.20240116-77598-2ir1kp sitelibdir\=./.gem.20240116-77598-2ir1kp
compiling autolink.c
compiling buffer.c
compiling rinku.c
compiling rinku_rb.c
compiling utf8.c
linking shared-object rinku.bundle
ld: warning: duplicate -rpath '/opt' ignored
ld: warning: search path '/Users/scottjg/.pkgx/ruby-lang.org/v3.2.2/lib/arm64-darwin23' not found

current directory: /usr/local/lib/ruby/gems/3.2.0/gems/rinku-2.0.6/ext/rinku
make DESTDIR\= sitearchdir\=./.gem.20240116-77598-2ir1kp sitelibdir\=./.gem.20240116-77598-2ir1kp install
/Users/builder/actions-runner/_work/_actions/pkgxdev/brewkit/v1/share/brewkit/install -c -m 0755 rinku.bundle ./.gem.20240116-77598-2ir1kp
make: /Users/builder/actions-runner/_work/_actions/pkgxdev/brewkit/v1/share/brewkit/install: No such file or directory
make: *** [install-so] Error 1
```
you can see it in the issue in the packaged ruby:
```
scottjg@scottjgs-MacBook-Air rewatch % grep -R actions- ~/.pkgx/ruby-lang.org/v3.2.2/lib/ruby/3.2.0/rbconfig.rb
/Users/scottjg/.pkgx/ruby-lang.org/v3.2.2/lib/ruby/3.2.0/rbconfig.rb:  CONFIG["INSTALL"] = '/Users/builder/actions-runner/_work/_actions/pkgxdev/brewkit/v1/share/brewkit/install -c'
/Users/scottjg/.pkgx/ruby-lang.org/v3.2.2/lib/ruby/3.2.0/rbconfig.rb:  CONFIG["MJIT_CC"] = "/Users/builder/actions-runner/_work/_actions/pkgxdev/brewkit/v1/share/toolchain/bin/clang"
```

2024-01-17 11:01 UTC, mxcl requested changes

2024-01-17 11:01 UTC, mxcl commented on projects/ruby-lang.org/package.yml
> +        -e 's|\(["'\'']\)/.*/brewkit/|TOPDIR \+ \1/../../pkgx.sh/brewkit/|g'
This package doesn’t depend on brewkit so this certainly is not going to work except via coincidence.

I think for now just replace with `/usr/bin/cc` and `/usr/bin/install`

2024-01-17 19:08 UTC, scottjg commented on projects/ruby-lang.org/package.yml
> +        -e 's|\(["'\'']\)/.*/brewkit/|TOPDIR \+ \1/../../pkgx.sh/brewkit/|g'
sure, no problem. this fix seems to work just as well for me.

2024-01-18 20:16 UTC, merged

2024-01-18 20:16 UTC, mxcl commented
Thanks for your dedication here!

2024-01-18 20:20 UTC, scottjg commented
i admit it's a little self-serving (i'd like my team to move off homebrew). but of course, happy to contribute when i can.

2024-01-18 20:22 UTC, jhheider commented
that kind of self-serving is 100% welcome; let us know if you hit real-world sticking points.

2024-01-18 20:34 UTC, mxcl commented
restocking https://github.com/pkgxdev/pantry/actions/runs/7575622483