+github.com/jpsim/SourceKitten
pkgxdev/pantry pull request #5199
Opened 2024-02-13 18:33 UTC by ArionThinker

2024-02-15 12:13 UTC, mxcl requested changes

2024-02-15 12:13 UTC, mxcl commented on projects/github.com/jpsim/SourceKitten/package.yml
> +  - patch -p1 < props/patch.diff
patches require comments justifying why they are necessary.

2024-02-15 12:45 UTC, ArionThinker commented on projects/github.com/jpsim/SourceKitten/package.yml
> +  - patch -p1 < props/patch.diff
I've added this comment and restricted the patch to version binding 👌🏻 

```
# https://github.com/jpsim/SourceKitten/pull/794 remove in release > 0.34.1
# fix this issue https://github.com/jpsim/SourceKitten/issues/793
- run: patch -p1 < props/patch.diff
  if: <=0.34.1
```

2024-02-15 16:15 UTC, mxcl approved these changes

2024-02-15 16:15 UTC, merged

2024-02-15 16:26 UTC, mxcl commented
Depends on a newer swift that macos 11 provides https://github.com/pkgxdev/pantry/actions/runs/7918947298/job/21618717961

Not sure the intricacies of this yet. That is: do we actually need this to depend on macOS 12 or can we provide a swift version that is newer?

2024-02-15 16:30 UTC, ArionThinker commented
> Depends on a newer swift that macos 11 provides https://github.com/pkgxdev/pantry/actions/runs/7918947298/job/21618717961
> 
> Not sure the intricacies of this yet. That is: do we actually need this to depend on macOS 12 or can we provide a swift version that is newer?

```
SourceKitten now requires Swift 5.6 or higher to build, and macOS 12
or higher to run.
```

from: https://github.com/jpsim/SourceKitten/releases/tag/0.33.0

2024-02-16 11:18 UTC, mxcl commented
k well we need to be able to specify these platform dependencies.